name: Staging deployment

on:
  push:
    branches: [ "main" ]

jobs:
  staging:

    runs-on: ubuntu-latest

    steps:
    - name: Execute SSH commmands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'jmacboy@${{ secrets.HOST }}'
        privateKey: ${{ secrets.SSH_KEY }}
        command: ls -lah
