name: Staging deployment

on:
  push:
    branches: [ "main" ]

jobs:
  staging:

    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
    
      - name: Stop the server
        run: ssh staging -vv 'sudo systemctl stop pedidos.service'

      - name: Check out the source
        run: ssh staging 'cd /var/www/pedidos-app && git fetch && git stash && git reset --hard origin/main && git stash pop'
      - name: Build source
        run: ssh staging 'cd /var/www/pedidos-app  && dotnet-ef database update  --project Pedidos.Infraestructure --startup-project Pedidos.WebApi --context Pedidos.Infraestructure.EF.Contexts.WriteDbContext && dotnet publish'
        
      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo systemctl start pedidos.service'
        
